### ISSUE TITLE
"name_filter" hack not showing up in NPM install

### ISSUE THREAD

**Issue by indolering** [joshbeal/node-namecoin#1]
For whatever reason, the "name_filter" hack in jsonrpc.js is not showing up in my NPM installed version of node-namecoin.

**Comment by joshbeal** [comment]
Published 0.1.4 with the fix

**Comment by indolering** [comment]
Do you know what is causing that problem?

**Comment by joshbeal** [comment]
I needed to publish the latest version. Is it still a problem?

**Comment by indolering** [comment]
I was asking why we need the hack in the first place.  I created the have but I have no idea why the function doesn't just work.  It would be better if we could track down the problem and submit an upstream fix ....
